Feature/post contract testing 03
wearearima/blog pull request #56
Opened 2020-10-13 10:12 UTC by jaguado-arima

2020-10-28 09:36 UTC, itelleria approved these changes

2020-10-28 09:36 UTC, itelleria commented on _posts/es/2020-10-15-playing-with-spring-cloud-contract.markdown
> +Empezaremos definiendo el acuerdo: escribiremos la especificación que tienen que cumplir _consumer_ y _producer_ para que la comunicación funcione correctamente. En Spring Cloud Contract se utiliza e
Dejaría sólo como fácil de leer. Hay bastante debate en twiter si yaml es un formato fácil de mantener o no. Por ejemplo https://twitter.com/emilyfhjiang/status/1310892923375046657

2020-10-28 10:05 UTC, itelleria requested changes

2020-10-28 10:05 UTC, itelleria commented on _posts/es/2020-10-15-playing-with-spring-cloud-contract.markdown
> +            <exclusion>
@jaguado-arima ¿para qué esta exclusión?

2020-10-28 10:05 UTC, itelleria commented on _posts/es/2020-10-15-playing-with-spring-cloud-contract.markdown
> +@AutoConfigureStubRunner(ids = { "eu.arima.tr:timeReports-producer:+:stubs:8083" })
@jaguado-arima explicaría qué tiene diferente este test respecto un test de Spring Boot tradicional. Por lo que veo hemos añadido la anotación `@AutoConfigureStubRunner` qué hace? ¿y para qué hacemos override de la propiedad `server.url`?

2020-10-28 10:05 UTC, itelleria commented on _posts/es/2020-10-15-playing-with-spring-cloud-contract.markdown
> +  _Para una **petición** con: un nombre de usuario y una fecha (cuyo formato también especificamos), la **respuesta** será: `status 200` y un `JSON` (cuyo contenido establecemos mediante un [fichero]
@jaguado-arima Esto en cursiva no se ve bien en Github. Tal vez luego en el post sí. Lo apunto por si acaso.

![image](https://user-images.githubusercontent.com/556304/97420151-3df91200-190b-11eb-84f9-70cc935131fd.png)

2020-10-28 10:31 UTC, jaguado-arima commented on _posts/es/2020-10-15-playing-with-spring-cloud-contract.markdown
> +            <exclusion>
ups, no me acuerdo. Lo miro

2020-10-28 10:33 UTC, jaguado-arima commented on _posts/es/2020-10-15-playing-with-spring-cloud-contract.markdown
> +@AutoConfigureStubRunner(ids = { "eu.arima.tr:timeReports-producer:+:stubs:8083" })
server.url porque me apetecía, sin más, porque por defecto se levanta el producer en 8081 y para no "pensar" que se está ejecutando contra el servicio real.
No creo que haga falta explicarlo no?

@AutoConfigureSubRunner, entiendo que es el que dice que coja la configuración de eu....timeReports-producer-xx-stub.jar y lo "despliegue" en 8083.
Quieres que lo mire bien y lo ponga explicado?

2020-10-28 10:34 UTC, jaguado-arima commented on _posts/es/2020-10-15-playing-with-spring-cloud-contract.markdown
> +  _Para una **petición** con: un nombre de usuario y una fecha (cuyo formato también especificamos), la **respuesta** será: `status 200` y un `JSON` (cuyo contenido establecemos mediante un [fichero]
En el blog se ve bien, de todas formas creo que le sobra un espacio

2020-10-28 10:56 UTC, jaguado-arima commented on _posts/es/2020-10-15-playing-with-spring-cloud-contract.markdown
> +            <exclusion>
pues parece que no sirve para nada, probablemente me lo dejaría de alguna prueba de algo, lo quito de aquí y del código

2020-10-29 09:37 UTC, jaguado-arima commented on _posts/es/2020-10-15-playing-with-spring-cloud-contract.markdown
> +@AutoConfigureStubRunner(ids = { "eu.arima.tr:timeReports-producer:+:stubs:8083" })
He quitado el puerto y he puesto miniexplicación: Una vez añadidas las dependencias ya podemos crear el WireMock basado en ese stub y crear nuestros tests. Nosotros lo haremos mediante la anotación `@AutoConfigureStubRunner` donde indicamos nuestro stub para que sea automáticamente descargado y registrado en el Wiremock. Un ejemplo podría ser: (aquí ya el ejemplo)

2020-10-29 14:35 UTC, merged